TopLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('account/', include('apps.accounts.urls', namespace='accounts')),
    path('userpanel/', include('apps.userpanel.urls', namespace='userpanel')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('forum/', include('apps.forum.urls', namespace='forum')),

    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت Toplearn"

apps/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='Register'),
    path('activeCode/<str:activecode>', ActiveCode.as_view(), name='ActiveCode'),
    path('login/', LoginUserView.as_view(), name='Login'),
    path('logout/', LogoutUserView.as_view(), name='Logout'),
    path('forgotpassword/', ForgotPasswordView.as_view(), name='ForgotPassword'),
    path('resetpassword/<str:activecode>', ResetPasswordView.as_view(), name='ResetPassword'),
]

apps/order/urls.py
from django.urls import path
from .views import ShowOrder, FinallyOrder, UseDiscount, OrdersList

app_name = 'order'
urlpatterns = [
    path('show_order/<int:order_id>', ShowOrder.as_view(), name='ShowOrder'),
    path('finaly_order/<int:order_id>', FinallyOrder.as_view(), name='FinallyOrder'),
    path('use_discount', UseDiscount.as_view(), name='UseDiscount'),
    path('orders_list', OrdersList.as_view(), name='OrdersList'),
]

apps/userpanel/urls.py
from django.urls import path
from .views import *

app_name = 'userpanel'
urlpatterns = [
    path('userpanel/', UserPanelInformationView.as_view(), name='UserPanelInformation'),
    path('editprofile/', EditProfileView.as_view(), name='EditProfile'),
    path('wallet/', WalletView.as_view(), name='Wallet'),
    path('master_panel/', MasterCoursesList.as_view(), name='MasterCoursesList'),
    path('master_episodes/<int:course_id>', MasterEpisodeList.as_view(), name='MasterEpisodeList'),
    path('add_episodes/<int:course_id>', AddEpisode.as_view(), name='AddEpisode'),
    path('dropzone_target/<int:course_id>', DropzoneTarget.as_view(), name='DropzoneTarget'),
]

templates/Partials/footer.html
<footer>
    <div class="top-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <section class="list">
                        <header><h4> دسترسی سریع</h4></header>
                        <ul>
                            <li><a href="">مشاهده تمامی دوره ها</a></li>
                            <li><a href="">قوانین خرید از سایت </a></li>
                            <li><a href="">راهنمای خرید از سایت </a></li>
                            <li><a href="">همکاری با تاپ لرن </a></li>
                            <li><a href="">کسب درآمد از تاپ لرن </a></li>
                            <li><a href="">ماهنامه طراحی وب</a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <section class="list">
                        <header><h4> دسترسی سریع</h4></header>
                        <ul>
                            <li><a href="">مشاهده تمامی دوره ها</a></li>
                            <li><a href="">قوانین خرید از سایت </a></li>
                            <li><a href="">راهنمای خرید از سایت </a></li>
                            <li><a href="">همکاری با تاپ لرن </a></li>
                            <li><a href="">کسب درآمد از تاپ لرن </a></li>
                            <li><a href="">ماهنامه طراحی وب</a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <section class="list">
                        <header><h4> دسترسی سریع</h4></header>
                        <ul>
                            <li><a href="">مشاهده تمامی دوره ها</a></li>
                            <li><a href="">قوانین خرید از سایت </a></li>
                            <li><a href="">راهنمای خرید از سایت </a></li>
                            <li><a href="">همکاری با تاپ لرن </a></li>
                            <li><a href="">کسب درآمد از تاپ لرن </a></li>
                            <li><a href="">ماهنامه طراحی وب</a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <section class="list">
                        <header><h4> دسترسی سریع</h4></header>
                        <ul>
                            <li><a href="">مشاهده تمامی دوره ها</a></li>
                            <li><a href="">قوانین خرید از سایت </a></li>
                            <li><a href="">راهنمای خرید از سایت </a></li>
                            <li><a href="">همکاری با تاپ لرن </a></li>
                            <li><a href="">کسب درآمد از تاپ لرن </a></li>
                            <li><a href="">ماهنامه طراحی وب</a></li>
                        </ul>
                    </section>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-footer">
        <div class="container">
            <p>
                تمامی حقوق مادی و معنوی این قالب متعلق به <a href=""> تاپ لرن </a> می باشد و هرگونه کپی برداری و انتشار غیر مجاز پیگرد قانونی دارد .
            </p>
        </div>
    </div>
</footer>

templates/Partials/messages.html
{% if messages %}
    {% for message in messages %}
        <h1 class="alert alert-{{ message.tags }}">{{ message }}</h1>
    {% endfor %}

{% endif %}

templates/Partials/meta_tags.html
<meta name="googlebot" content="index,follow">
<meta name="robots" content="noodp,noydir">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">

templates/Partials/sidebar.html
<aside>

    <div class="avatar-layer">
        <div class="img-layer">
            <a href="" class="change-image"><i class="zmdi zmdi-edit"></i></a>
            {% if user.image_name %}
                <img src="{{ media_url }}{{ user.image_name }}"
                     class="thumbnail" style="max-width:150px">
            {% else %}
                <img src="{{ media_url }}images/UserAvatar/Default.jpg" class="thumbnail"
                     style="max-width:150px">
            {% endif %}

        </div>
        <div class="detail">
            <span style="font-family: Helvetica;"> {{ user.username }} </span>
            <span> عضویت : {{ user.get_register_date_shamsi }}</span>
        </div>
    </div>

    <section>
        <header><h3> میز کار </h3></header>
        <div class="inner">
            <ul>
                <li><a href="{% url 'userpanel:UserPanelInformation' %}"> مشاهده حساب کابری </a></li>
                <li><a href="{% url 'userpanel:EditProfile' %}"> ویرایش حساب کابری </a></li>
                <li><a href="/UserPanel/ChangePassword"> تغییر رمز عبور </a></li>
                <li><a href="{% url 'userpanel:Wallet' %}"> کیف پول شما </a></li>
                <li><a href="{% url 'order:OrdersList' %}"> فاکتور های شما </a></li>
                <li><a href=""> تنظیمات حساب کاربری </a></li>
                <li><a href="{% url 'accounts:Logout' %}"> خروج از حساب کاربری </a>
                </li>
            </ul>
        </div>
    </section>
    {% if perms.course.master_panel %}
        <section>
        <header><h3> پنل مدرس </h3></header>
        <div class="inner">
            <ul>
                <li><a href="{% url 'userpanel:MasterCoursesList' %}" > مدیریت دوره ها </a></li>

            </ul>
        </div>
        </section>
    {% endif %}
</aside>

templates/Partials/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-rtl.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'noUiSlider/nouislider.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/CustomStyle.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/ui-lightness/jquery-ui.min.css">
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />