TopLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('account/', include('apps.accounts.urls', namespace='accounts')),
    path('userpanel/', include('apps.userpanel.urls', namespace='userpanel')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('forum/', include('apps.forum.urls', namespace='forum')),

    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت Toplearn"

apps/course/urls.py
from django.urls import path
from .views import CourseGroupMenu, GetSubGroupsJson, CourseList, ShowCourse, BuyCourse, DownloadFiles, CreateComment, \
    show_comments, ShowCourseVote, add_vote

app_name = 'course'
urlpatterns = [
    path('course_group_menu', CourseGroupMenu, name='CourseGroupMenu'),
    path('sub_groups_json/<int:id>', GetSubGroupsJson, name='GetSubGroupsJson'),
    path('course_list', CourseList.as_view(), name='Courses'),
    path('show_course/<int:id>', ShowCourse.as_view(), name='ShowCourses'),
    path('buy_course/<int:course_id>', BuyCourse.as_view(), name='BuyCourses'),
    path('download_episodes/<int:episode_id>', DownloadFiles.as_view(), name='download_episodes'),
    path('create_comment/', CreateComment.as_view(), name='CreateComment'),
    path('show_comments/<int:course_id>', show_comments, name='ShowComments'),
    path('show_votes/<int:course_id>', ShowCourseVote.as_view(), name='ShowCourseVote'),
    path('add_vote/<int:course_id>', add_vote, name='AddVote'),
]

apps/userpanel/urls.py
from django.urls import path
from .views import *

app_name = 'userpanel'
urlpatterns = [
    path('userpanel/', UserPanelInformationView.as_view(), name='UserPanelInformation'),
    path('editprofile/', EditProfileView.as_view(), name='EditProfile'),
    path('wallet/', WalletView.as_view(), name='Wallet'),
    path('master_panel/', MasterCoursesList.as_view(), name='MasterCoursesList'),
    path('master_episodes/<int:course_id>', MasterEpisodeList.as_view(), name='MasterEpisodeList'),
    path('add_episodes/<int:course_id>', AddEpisode.as_view(), name='AddEpisode'),
    path('dropzone_target/<int:course_id>', DropzoneTarget.as_view(), name='DropzoneTarget'),
]

apps/course/models.py
import os
from uuid import uuid4
import jdatetime
from admin_decorators import short_description
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.db.models.signals import pre_delete, pre_save, post_save
from django.dispatch import receiver
from sorl.thumbnail import get_thumbnail
from TopLearn.settings import MEDIA_ROOT
from apps.accounts.models import User
from .utils import compact_and_resize_image


class CourseGroup(models.Model):
    groupTitle = models.CharField(max_length=200, verbose_name='عنوان گروه')
    parent = models.ForeignKey("CourseGroup", blank=True, null=True, on_delete=models.CASCADE, related_name='SubGroups', verbose_name=' گروه والد')
    is_active = models.BooleanField(default=False, verbose_name='وضعیت (فعال/غیرفعال)')

    def __str__(self):
        return self.groupTitle

    class Meta:
        verbose_name = 'گروه دوره ها'
        verbose_name_plural = 'گروه های دوره ها'
        db_table = 't_course_groups'


class CourseStatus(models.Model):
    statusTitle = models.CharField(max_length=150, verbose_name='عنوان وضعیت دوره')

    def __str__(self):
        return self.statusTitle

    class Meta:
        verbose_name = 'وضعیت دوره'
        verbose_name_plural = 'وضعیت دوره'
        db_table = 't_course_status'


class CourseLevel(models.Model):
    levelTitle = models.CharField(max_length=150, verbose_name='عنوان سطح دوره')

    def __str__(self):
        return self.levelTitle

    class Meta:
        verbose_name = 'سطح دوره'
        verbose_name_plural = 'سطح دوره'
        db_table = 't_course_level'


def upload_course_image(instance, filename):
    filename, ext = os.path.splitext(filename)
    path_output = f"images/course/image/{uuid4()}{ext}"
    try:
        course = Course.objects.get(id=instance.id)
        if course.courseImageName is not None:
            image_path = MEDIA_ROOT + str(course.courseImageName)
            if os.path.exists(image_path):
                os.remove(image_path)
        return path_output
    except Course.DoesNotExist:
        return path_output


def upload_course_demo(instance, filename):
    filename, ext = os.path.splitext(filename)
    try:
        course = Course.objects.get(id=instance.id)
        if course.demoFileName is not None:
            demo_path = MEDIA_ROOT + str(course.demoFileName)
            if os.path.exists(demo_path):
                os.remove(demo_path)
        return f"images/course/demos/{uuid4()}{ext}"
    except Course.DoesNotExist:
        return f"images/course/demos/{uuid4()}{ext}"


class Course(models.Model):
    courseTitle = models.CharField(max_length=200, verbose_name='عنوان دوره')
    description = RichTextUploadingField(config_name='super', verbose_name='شرح دوره')
    price = models.PositiveIntegerField(verbose_name='قیمت دوره')
    tags = models.CharField(max_length=500, verbose_name='کلمات کلیدی')
    courseImageName = models.ImageField(upload_to=upload_course_image, verbose_name='تصویر دوره')
    createDate = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')
    updateDate = models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')
    demoFileName = models.FileField(upload_to=upload_course_demo, verbose_name='ویدیو دمو دوره')
    group = models.ForeignKey(CourseGroup, on_delete=models.CASCADE, related_name='courses_of_group', verbose_name='گروه اصلی')
    subGroup = models.ForeignKey(CourseGroup, null=True, blank=True, on_delete=models.CASCADE, related_name='courses_of_subgroup', verbose_name='گروه فرعی')
    courseStatus = models.ForeignKey(CourseStatus, on_delete=models.CASCADE, related_name='courses_of_status', verbose_name='وضعیت دوره')
    courseLevel = models.ForeignKey(CourseLevel, on_delete=models.CASCADE, related_name='courses_of_level', verbose_name='سطح دوره')
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_of_teacher', verbose_name='مدرس')
    user = models.ManyToManyField(User, related_name='courses_of_user', verbose_name='کاربرانی که دوره رو تهیه کردن')
    is_active = models.BooleanField(default=False, verbose_name='وضعیت (فعال/غیرفعال)')

    def __str__(self):
        return f"نام دوره: {self.courseTitle}"

    @property
    def base_courseImageName(self):
        return os.path.basename(self.courseImageName.name)

    def get_createDate_shamsi(self):
        jdatetime_obj = jdatetime.datetime.fromgregorian(datetime=self.createDate)
        return jdatetime_obj.strftime('%Y/%m/%d')

    @short_description('آخرین بروزرسانی')
    def get_updateDate_shamsi(self):
        jdatetime_obj = jdatetime.datetime.fromgregorian(datetime=self.updateDate)
        return jdatetime_obj.strftime('%Y/%m/%d')

    class Meta:
        permissions = [
            ("master_panel", "پنل مدرس")
        ]
        indexes = [
            models.Index(fields=['-createDate']),
            models.Index(fields=['-updateDate']),
        ]
        verbose_name = 'دوره'
        verbose_name_plural = 'دوره ها'
        db_table = 't_courses'

    # def save(self, *args, **kwargs):
    #     if self.courseImageName:
    #         self.courseImageName = get_thumbnail(self.courseImageName, '500x600', quality=99, format='JPEG')
    #     super(MyPhoto, self).save(*args, **kwargs)


@receiver(post_save, sender=Course)
def thumbnail_creator(sender, instance, *args, **kwargs):
    course = Course.objects.get(id=instance.id)
    if instance.courseImageName:
        compact_and_resize_image(course.courseImageName, 200)
    #thumbnail = get_thumbnail(course.courseImageName, '200x150', quality=99, format='JPEG')
    # thumbnail.save('/path/to/save/thumbnail.jpg')


@receiver(pre_delete, sender=Course)
def image_delete_handler(sender, instance, *args, **kwargs):
    if instance.courseImageName:
        instance.courseImageName.delete()
    if instance.demoFileName:
        instance.demoFileName.delete()

## Episode Model ================================================================================================


def upload_episode_file(instance, filename):
    return f"coursefiles/{filename}"


class Episode(models.Model):
    episodeTitle = models.CharField(max_length=150, verbose_name='عنوان قسمت')
    episodeTime = models.DurationField(verbose_name='زمان')
    is_free = models.BooleanField(default=False, verbose_name='رایگان بودن')
    episodefilename = models.FileField(upload_to=upload_episode_file, verbose_name='فایل قسمت')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='episodes', verbose_name='دوره مربوطه')

    def __str__(self):
        return self.episodeTitle

    def save(self, *args, **kwargs):
        try:
            episode = Episode.objects.get(id=self.id)
            if os.path.exists(MEDIA_ROOT + str(episode.episodefilename)) and self.episodefilename and (episode.episodefilename != self.episodefilename):
                episode.episodefilename.delete(save=False)
        except Episode.DoesNotExist:
            pass
        super(Episode, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'قسمت'
        verbose_name_plural = 'قسمت ها'
        db_table = 't_episodes'


class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments', verbose_name='دوره')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name='کاربر ثبت کننده نظر')
    comment = models.TextField(max_length=700, verbose_name='متن نظر')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نظر')
    is_admin_read = models.BooleanField(default=False, verbose_name='دیده شدن توسط ادمین')

    def __str__(self):
        return f"نظر کاربر {self.user.username} برای دوره {self.course.courseTitle}"

    def get_created_date_shamsi(self):
        jdatetime_obj = jdatetime.datetime.fromgregorian(datetime=self.created_date)
        return jdatetime_obj.strftime('%Y/%m/%d')

    class Meta:
        ordering = ['-created_date']
        verbose_name = 'نظر'
        verbose_name_plural = 'نظر ها'
        db_table = 't_comments'


class CourseVote(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='vote', verbose_name='دوره')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vote', verbose_name='کاربر ثبت کننده لایک')
    vote = models.BooleanField(default=False, verbose_name='وضعیت پسندیدن')
    vote_time = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')

    def __str__(self):
        return f"وضعیت پسندیدن کاربر {self.user.username} برای دوره {self.course.courseTitle}"

    class Meta:
        verbose_name = 'پسند'
        verbose_name_plural = 'پسند ها'
        db_table = 't_votes'

templates/UserPanel_app/AddEpisode.html
{% extends "mainTemplate.html" %}

{% block title %}
    افزودن قسمت جدید
{% endblock title %}

{% block content %}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
            <li class="breadcrumb-item active" aria-current="page">افزودن قسمت جدید</li>
        </ul>
    </nav>
</div>

<main>
    <div class="container">
        <div class="user-account">
            <div class="row">
                <div class="col-md-3 col-sm-4 col-xs-12">
                    <partial name="_SideBar" />
                </div>
                <div class="col-md-9 col-sm-8 col-xs-12">
                    <section class="user-account-content">
                        <header><h1> افزودن قسمت جدید </h1></header>
                        <div class="inner form-layer">
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.course_id }}
                                {{ form.episodefilename }}
                                <div class="row">
                                    <div class="col-md-6 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="username"><i class="zmdi zmdi-file-text"></i></span>
                                            {{ form.title }}
                                            {{ form.title.errors }}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="zmdi zmdi-time"></i></span>
                                            {{ form.episodeTime }}
                                            {{ form.episodeTime.errors }}
                                        </div>
                                    </div>
                                    <div class="col-md-6 form-group">
                                        <label> رایگان است {{ form.is_free }}</label>

                                    </div>
                                    <div class="dropzone col-md-10 form-group" id="my-dropzone">
                                        <div class="fallback">
                                            <input name="files" type="file" multiple/>
                                        </div>
                                        <div class="dz-message">
                                            <i class="zmdi zmdi-upload"></i>
                                            <span>فایل خود را انتخاب و یا به داخل جعبه بیندازید</span>
                                        </div>
                                    </div>
                                    <div class="col-md-7 form-group">
                                        <button id="SubmitBtn" class="btn btn-success"> افزودن قسمت </button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block scripts %}
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function DropzoneParameterName() {
            return 'files';
        }

        Dropzone.options.myDropzone = {
            url: "/userpanel/dropzone_target/{{ form.course_id.value }}",
            headers: { 'X-CSRFToken': '{{ csrf_token }}' },
            parallelUploads: 1, // How Many Files process in parallel
            uploadMultiple: true, // Add Multiple To fallback input - Cant Use With chunking
            maxFilesize: 100000000, // In byte - 100000000 is 100 mb
            paramName: DropzoneParameterName, // if uploadMultiple is true set as true for add [] in name
            maxFiles: 1, // If not null defines how many files this Dropzone handles. If it exceeds, the event maxfilesexceeded will be called.
            acceptedFiles: '.mp4, .mkv', // default is null - This is a comma separated list of mime types or file extensions [image/*,application/pdf,.psd]
            init: function() {
                this.on("errormultiple",
                    function(file, message) {
                        swal("Error", message, "error");
                    });
                this.on("sendingmultiple",
                    function(file) {
                        $("#SubmitBtn").prop("disabled", true);
                    });
                this.on("queuecomplete",
                    function(file) {
                        $("#SubmitBtn").prop("disabled", false);
                    });
                this.on("successmultiple",
                    function(file, response) {
                        if (response.status === "Success") {
                            $("#id_episodefilename").val(response.data);
                        } else {
                            swal("Error", "!عملیات با خطا مواجه شد .", "error");
                        }
                    });
                this.on("maxfilesreached",
                    function(file) {
                        this.removeEventListeners();
                    });
            }
        }
    </script>
{% endblock %}

templates/UserPanel_app/EditProfile.html
{% extends "mainTemplate.html" %}

{% block title %}
    ویرایش پروفایل
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
                <li class="breadcrumb-item active" aria-current="page">ویرایش پروفایل {{ user.username }} </li>
            </ul>
        </nav>
    </div>

    <main>
        <div class="container">
            <div class="user-account">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        {% include 'Partials/sidebar.html' %}
                    </div>
                    <div class="col-md-9 col-sm-8 col-xs-12">
                        <section class="user-account-content">
                            <header><h1> ویرایش حساب کاربری </h1></header>
                            <div class="inner form-layer">
                                <form action="{% url 'userpanel:EditProfile' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                    {{ form.image_name }}
                                    <div class="row">
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon" id="username"><i
                                                        class="zmdi zmdi-account"></i></span>
                                                {{ form.username }}
                                            </div>
                                            {{ form.errors.username }}
                                        </div>
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon" id="email-address"><i
                                                        class="zmdi zmdi-email"></i></span>
                                                {{ form.email }}
                                            </div>
                                            {{ form.errors.email }}
                                        </div>

                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <p class="help-block">آواتار</p>
                                            {% if user.image_name %}
                                                <img src="{{ media_url }}{{ user.image_name }}"
                                                     class="thumbnail" style="max-width:150px">
                                            {% else %}
                                                <img src="{{ media_url }}images/UserAvatar/Default.jpg"
                                                     class="thumbnail" style="max-width:150px">
                                            {% endif %}
                                            {{ form.image }}
                                        </div>
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <button class="btn btn-success"> ویرایش اطلاعات</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/UserPanel_app/EpisodeList.html
{% extends "mainTemplate.html" %}

{% block title %}
   مدیریت قسمت ها
{% endblock title %}

{% block content %}
    <div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
            <li class="breadcrumb-item active" aria-current="page">مدیریت قسمت ها</li>
        </ul>
    </nav>
</div>

<main>
    <div class="container">
        <div class="user-account">
            <div class="row">
                <div class="col-md-3 col-sm-4 col-xs-12">
                    {% include 'Partials/sidebar.html' %}
                </div>
                <div class="col-md-9 col-sm-8 col-xs-12">
                    <section class="user-account-content">
                        <header><h1> مدیریت قسمت ها </h1></header>
                        <a class="btn btn-success" href="{% url 'userpanel:AddEpisode' course_id=course.id %}">افزودن قسمت جدید</a>
                        <div class="inner form-layer">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>عنوان</th>
                                        <th>زمان</th>
                                        <th>وضعیت</th>
                                        <th>دستورات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for episode in course.episodes.all %}
                                        <tr>
                                            <td>
                                                {{ episode.episodeTitle }}
                                            </td>
                                            <td>{{ episode.episodeTime }}</td>
                                            <td>
                                                {% if episode.is_free %}
                                                    <span class="success">رایگان</span>
                                                {% else %}
                                                    <span class="info">نقدی</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                <a class="btn btn-info btn-block" href="{% url 'course:download_episodes' episode_id=episode.id %}">دانلود</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/UserPanel_app/MasterCoursesList.html
{% extends "mainTemplate.html" %}

{% block title %}
    لیست دوره های مدرس
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
                <li class="breadcrumb-item active" aria-current="page">لیست دوره های مدرس</li>
            </ul>
        </nav>
    </div>

    <main>
        <div class="container">
            <div class="user-account">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        {% include 'Partials/sidebar.html' %}
                    </div>
                    <div class="col-md-9 col-sm-8 col-xs-12">
                        <section class="user-account-content">
                            <header><h1> لیست دوره های مدرس</h1></header>
                            <div class="inner form-layer">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>عنوان</th>
                                        <th>وضعیت</th>
                                        <th>تعداد قسمت ها</th>
                                        <th>دستورات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for course in courses %}
                                        <tr>
                                            <td>
                                                {{ course.courseTitle }}
                                            </td>
                                            <td>{{ course.courseStatus.statusTitle }}</td>

                                            <td>{{ course.episodes.count }}</td>
                                            <td>
                                                <a class="btn btn-info btn-block" href="{% url 'userpanel:MasterEpisodeList' course_id=course.id %}">مدیریت قسمت
                                                    ها</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/UserPanel_app/UserPanelinfo.html
{% extends "mainTemplate.html" %}

{% block title %}
    پنل کاربری
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
                <li class="breadcrumb-item active" aria-current="page"> پنل کاربری {{ user.username }}</li>
            </ul>
        </nav>
    </div>

    <main>
        <div class="container">
            <div class="user-account">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        {% include 'Partials/sidebar.html' %}
                    </div>
                    <div class="col-md-9 col-sm-8 col-xs-12">
                        <section class="user-account-content">
                            <header><h1> داشبورد </h1></header>
                            <div class="inner">
                                <div class="account-information">
                                    <h3> اطلاعات کاربری </h3>
                                    <ul style="font-family: Helvetica ;">
                                        <li><i class="zmdi zmdi-assignment-account"></i> نام کاربری : {{ user.username }}
                                        </li>
                                        <li><i class="zmdi zmdi-email"></i> ایمیل : {{ user.email }}</li>
                                        <li><i class="zmdi zmdi-calendar-check"></i> تاریخ عضویت :
                                            {{ user.get_register_date_shamsi }}
                                        </li>
                                        <li><i class="zmdi zmdi-money"></i> موجودی حساب : {{ user.balance_wallet }}</li>
                                    </ul>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/UserPanel_app/Wallet.html
{% extends "mainTemplate.html" %}
{% load humanize %}

{% block title %}
    کیف پول شما
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
                <li class="breadcrumb-item active" aria-current="page">کیف پول {{ user.username }}</li>
            </ul>
        </nav>
    </div>

    <main>
        <div class="container">
            <div class="user-account">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        {% include 'Partials/sidebar.html' %}
                    </div>
                    <div class="col-md-9 col-sm-8 col-xs-12">
                        <section class="user-account-content">
                            <header><h1> کیف پول شما </h1></header>
                            <div class="inner form-layer">

                                <form action="{% url 'userpanel:Wallet' %}" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon" id="password"><i
                                                        class="zmdi zmdi-balance-wallet"></i></span>
                                                {{ form.amount }}
                                            </div>
                                        </div>

                                        {{ form.errors.amount }}
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <button class="btn btn-success">شارژ کیف پول</button>
                                        </div>
                                    </div>
                                </form>
                                <hr/>
                                <table class="table table-bordered">
                                    <tr>
                                        <th>مبلغ</th>
                                        <th>نوع تراکنش</th>
                                        <th>تاریخ</th>
                                        <th>شرح</th>

                                    </tr>

                                    {% for wallet in user.get_wallets_user %}
                                        <tr>
                                            <th>{{ wallet.amount | intcomma }} تومان </th>
                                            <th class="text-danger">{{ wallet.type__type_id }}</th>
                                            <th>{{ wallet.get_created_date_shamsi }}</th>
                                            <th>{{ wallet.description }}</th>

                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}