TopLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('account/', include('apps.accounts.urls', namespace='accounts')),
    path('userpanel/', include('apps.userpanel.urls', namespace='userpanel')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('forum/', include('apps.forum.urls', namespace='forum')),

    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت Toplearn"

apps/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='Register'),
    path('activeCode/<str:activecode>', ActiveCode.as_view(), name='ActiveCode'),
    path('login/', LoginUserView.as_view(), name='Login'),
    path('logout/', LogoutUserView.as_view(), name='Logout'),
    path('forgotpassword/', ForgotPasswordView.as_view(), name='ForgotPassword'),
    path('resetpassword/<str:activecode>', ResetPasswordView.as_view(), name='ResetPassword'),
]

apps/forum/urls.py
from django.urls import path
from .views import CreateQuestion, ListQuestion, ShowQuestion, AddAnswer, SelectIsTrueAnswer

app_name = 'forum'
urlpatterns = [
    path('add_question/<int:course_id>', CreateQuestion.as_view(), name='CreateQuestion'),
    path('', ListQuestion.as_view(), name='ListQuestion'),
    path('show_question/<int:question_id>', ShowQuestion.as_view(), name='ShowQuestion'),
    path('add_answer/', AddAnswer.as_view(), name='AddAnswer'),
    path('select_true_answer', SelectIsTrueAnswer.as_view(), name='SelectIsTrueAnswer'),
]

apps/userpanel/urls.py
from django.urls import path
from .views import *

app_name = 'userpanel'
urlpatterns = [
    path('userpanel/', UserPanelInformationView.as_view(), name='UserPanelInformation'),
    path('editprofile/', EditProfileView.as_view(), name='EditProfile'),
    path('wallet/', WalletView.as_view(), name='Wallet'),
    path('master_panel/', MasterCoursesList.as_view(), name='MasterCoursesList'),
    path('master_episodes/<int:course_id>', MasterEpisodeList.as_view(), name='MasterEpisodeList'),
    path('add_episodes/<int:course_id>', AddEpisode.as_view(), name='AddEpisode'),
    path('dropzone_target/<int:course_id>', DropzoneTarget.as_view(), name='DropzoneTarget'),
]

templates/mainTemplate.html
{% load static %}
{% load render_partial %}
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}|تاپ لرن</title>
    {% include 'Partials/meta_tags.html' %}
    {% include 'Partials/styles.html' %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>
<script src="{% static 'js/modernizr-custom.js' %}"></script>

<div class="landing-layer">
    <div class="container">
        <nav>
            <div class="row">
                <div class="col-sm-6 col-xs-12">
                    <ul>
                        <li>
                            <a href=""> همکاری در فروش </a>
                            <a href=""> درباره ما </a>
                            <a href=""> تماس با ما </a>
                            <a href="{% url 'forum:ListQuestion'%}"> انجمن </a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6 col-xs-12">
                    <div class="clientarea">
                        {% if user.is_authenticated %}
                        <div class="loggein ">
                            <i class="zmdi zmdi-account"></i><a href="{% url 'userpanel:UserPanelInformation' %}"> {{ user.username }}  خوش آمدی </a>/
                            <a href="{% url 'accounts:Logout'%}"> خروج </a>
                        </div>
                        {% else %}
                        <div class="signin">
                            <i class="zmdi zmdi-account"></i>
                            <a href="{% url 'accounts:Login' %}"> ورود </a> /
                            <a href="{% url 'accounts:Register' %}"> عضویت </a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        {% block search_box %}
        {% endblock search_box %}
    </div>
</div>

<!-- main manu -->
{% render_partial 'course:CourseGroupMenu' %}
<!-- /main manu -->
{% include "Partials/messages.html" %}
<!-- content -->
{% block content %}
{% endblock content %}
<!-- /content -->

<!-- footer -->
{% include 'Partials/footer.html' %}
<!-- /footer -->

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/jquery.validate.unobtrusive.js' %}"></script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>