TopLearn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('account/', include('apps.accounts.urls', namespace='accounts')),
    path('userpanel/', include('apps.userpanel.urls', namespace='userpanel')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('forum/', include('apps.forum.urls', namespace='forum')),

    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت Toplearn"

apps/course/urls.py
from django.urls import path
from .views import CourseGroupMenu, GetSubGroupsJson, CourseList, ShowCourse, BuyCourse, DownloadFiles, CreateComment, \
    show_comments, ShowCourseVote, add_vote

app_name = 'course'
urlpatterns = [
    path('course_group_menu', CourseGroupMenu, name='CourseGroupMenu'),
    path('sub_groups_json/<int:id>', GetSubGroupsJson, name='GetSubGroupsJson'),
    path('course_list', CourseList.as_view(), name='Courses'),
    path('show_course/<int:id>', ShowCourse.as_view(), name='ShowCourses'),
    path('buy_course/<int:course_id>', BuyCourse.as_view(), name='BuyCourses'),
    path('download_episodes/<int:episode_id>', DownloadFiles.as_view(), name='download_episodes'),
    path('create_comment/', CreateComment.as_view(), name='CreateComment'),
    path('show_comments/<int:course_id>', show_comments, name='ShowComments'),
    path('show_votes/<int:course_id>', ShowCourseVote.as_view(), name='ShowCourseVote'),
    path('add_vote/<int:course_id>', add_vote, name='AddVote'),
]

apps/forum/urls.py
from django.urls import path
from .views import CreateQuestion, ListQuestion, ShowQuestion, AddAnswer, SelectIsTrueAnswer

app_name = 'forum'
urlpatterns = [
    path('add_question/<int:course_id>', CreateQuestion.as_view(), name='CreateQuestion'),
    path('', ListQuestion.as_view(), name='ListQuestion'),
    path('show_question/<int:question_id>', ShowQuestion.as_view(), name='ShowQuestion'),
    path('add_answer/', AddAnswer.as_view(), name='AddAnswer'),
    path('select_true_answer', SelectIsTrueAnswer.as_view(), name='SelectIsTrueAnswer'),
]

templates/Forum_app/CreateQuestion.html
{% extends "mainTemplate.html" %}
{% load static %}

{% block title %}
    پرسش
{% endblock title %}

{% block content %}

    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">تاپ لرن</a></li>
                <li class="breadcrumb-item active" aria-current="page">پرسش</li>
            </ul>
        </nav>
    </div>

    <div class="row ">
        <div class="col-md-3"></div>
        <form method="post">
            {% csrf_token %}
            {{ form.course_id }}
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading"> پرسش</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label>عنوان سوال</label>
                            {{ form.title }}
                            {{ form.errors.title }}
                        </div>
                        <div class="form-group">
                            <label for={{ form.body.id_for_label }}>متن سوال</label>
                            <br>
                            {{ form.body }}
                            {{ form.errors.title }}
                        </div>

                        <div class="row" style="margin:2px">
                            <p>
                                <input type="submit" value="ارسال سوال" class="btn btn-success"/>
                            </p>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

templates/Forum_app/ListQuestions.html
{% extends "mainTemplate.html" %}
{% load static %}

{% block title %}
    پرسش
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/"> تاپ لرن </a></li>
                <li class="breadcrumb-item"><a href="{% url 'forum:ListQuestion' %}"> پرسش و پاسخ ها</a></li>
            </ul>
        </nav>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="top-bar">
                    <div class="row">
                        <div class="col-md-5 col-sm-12 col-xs-12 pull-right">
                            <form method="get">
                                {% if course != None %}
                                    <input type="hidden" value="{{ course.id }}" name="course_id"/>
                                {% endif %}
                                <div class="input">
                                    <input class="searchinput" type="text" name="filter" placeholder="عنوان پرسش مورد نظر ...">
                                    <button class="searchsub"><i class="zmdi zmdi-search"></i></button>
                                </div>
                            </form>
                        </div>
                        {% if course != None %}
                            {% if user.is_authenticated %}
                                {% if course.price != 0 and is_user_in_course %}
                                    <div class="col-md-3 col-sm-12 col-xs-12 pull-right">
                                        <a class="btn btn-info" href="{% url 'forum:CreateQuestion' course_id=course.id %}">پرسیدن
                                            سوال</a>
                                    </div>
                                {% else %}
                                    <div class="col-md-3 col-sm-12 alert alert-danger">
                                        شما این دوره رو خریداری نکردید
                                    </div>
                                {% endif %}
                            {% else %}
                                <div class="col-md-3 col-sm-12 alert alert-danger">
                                    برای پرسیدن سوال وارد سایت شوید
                                </div>
                            {% endif %}
                        {% endif %}


                    </div>
                </div>
                <div class="inner" style="margin-top: 25px;">
                    {% for question in questions %}
                    <div class="panel ">
                        <div class="panel-heading">
                            {% if question.user.image_name %}
                                <img src="{{ media_url }}{{ question.user.image_name }}" style="max-width: 40px; border-radius: 20px;"/>
                            {% else %}
                                <img src="{{ media_url }}/images/UserAvatar/Default.jpg" style="max-width: 40px; border-radius: 20px;"/>
                            {% endif %}
                            {{ question.user.username }} | {{ question.get_created_date_shamsi }}

                            <h1 style="margin:7px">
                                <a href="/forum/show_question/{{ question.id }}">
                                    عنوان: {{ question.title }}
                                </a>
                            </h1>
                            <div class="text-muted pull-left">
                                <a class="btn btn-secondary" href="{% url 'course:ShowCourses' id=question.course.id %}">{{ question.course.courseTitle }}</a>
                            </div>
                        </div>
                        <div class="panel-body">
                            {{ questions.body }}
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

templates/Forum_app/ShowQuestion.html
{% extends "mainTemplate.html" %}
{% load static %}

{% block title %}
    پرسش
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/"> تاپ لرن </a></li>
                <li class="breadcrumb-item"><a href="/Forum/Questions"> پرسش و پاسخ </a></li>
                <li class="breadcrumb-item active" aria-current="page"> {{ question.title }} </li>
            </ul>
        </nav>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="inner">
                    <div class="panel">
                        <div class="panel-heading">
                            <h1>{{ question.title }}</h1>
                        </div>
                        <div class="panel-body">
                            {% autoescape off %}
                                {{ question.body }}
                            {% endautoescape %}
                        </div>
                        <div class="panel-footer">
                            {% if question.user.image_name %}
                                <img src="{{ media_url }}{{ question.user.image_name }}" style="max-width: 50px; border-radius: 20px;"/>
                            {% else %}
                                <img src="{{ media_url }}images/UserAvatar/Default.jpg" style="max-width: 50px; border-radius: 20px;"/>
                            {% endif %}
                            {{ question.user.username }} | {{ question.get_created_date_shamsi }}
                        </div>
                    </div>
                </div>

                <br/>

                <div class="inner" style="margin-top: 25px;">
                    {% for answer in question.answers.all %}
                        <div class="panel {% if answer.is_true %}is_true{% endif %}">
                            <div class=" panel-heading">
                                {% if answer.user.image_name %}
                                    <img src="{{ media_url }}{{ answer.user.image_name }}" style="max-width: 40px; border-radius: 20px;"/>
                                {% else %}
                                    <img src="{{ media_url }}images/UserAvatar/Default.jpg" style="max-width: 40px; border-radius: 20px;"/>
                                {% endif %}
                                {{ answer.user.username }} | {{ question.get_created_date_shamsi }}
                            </div>
                            <div class="panel-body">
                                {% autoescape off %}
                                    {{ answer.answer_body }}
                                {% endautoescape %}
                                {% if user.is_authenticated and question.user == user %}
                                    <p>
                                        <a class="btn btn-success pull-left"
                                           href="{% url 'forum:SelectIsTrueAnswer' %}?question_id={{ question.id }}&answer_id={{ answer.id }}">پاسخ صحیح</a>
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}

                </div>

                {% if user.is_authenticated %}
                    <div class="inner" style="margin-top: 25px;">
                        <div class="panel">
                            <div class="panel-heading">
                                <h1 style="font-size: 18px;" class="text-success text-muted">افزودن پاسخ جدید</h1>
                            </div>
                            <div class="panel-body">
                                <form action="{% url 'forum:AddAnswer' %}" method="post">
                                    {% csrf_token %}
                                    {{ form.question_id }}
                                    <div class="form-group">
                                        {{ form.answer_body }}
                                        <button class="btn btn-block btn-success" style="margin-top: 20px; height: 50px; font-size:15px;" type="submit">ثبت پاسخ
                                            شما
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="alert alert-danger">
                        برای پاسخ دادن به این سوال باید لاگین کنید!
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}